apiVersion: v1
kind: Service
metadata:
  name: discovery-service
  labels:
    app:discovery-service
spec:
  type: ClusterIP
  selector:
    app: discovery-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8761