############## Info properties ###############
info:
  system: '@project.artifactId@'
  app:
    name: '@project.artifactId@'
    version: '@project.version@'
############## Spring App properties ###############
spring:
  application:
    name: '@project.artifactId@'
  lifecycle:
    timeout-per-shutdown-phase: 15s  
  cloud:
    function:
      definition: backendFunctions
  ############## Datasource configuration H2 ###############
  r2dbc:
    username: sa
    password: 
    url: r2dbc:h2:file:///./target/data/functions/products-db    
    pool:
      max-create-connection-time: 5s
      initial-size: 5
      max-size: 10
  h2:
    console.enabled: true
    console.path: /h2-console
    console.settings.trace: true      
############## Log properties ###############
logging:
  level:
    '[com.craftsman.restservice]': DEBUG
############## Server properties ###############
server:
  port: 9103