############## Spring properties ###############    
spring:
  application:
    name: '@project.artifactId@'
  lifecycle:
    timeout-per-shutdown-phase: 15s
############## Info properties ###############
info:
  app:
    name: '@project.artifactId@'
    version: '@project.version@'
############## Log properties ###############
logging:
  level:
    '[com.craftsman.discoveryservice]': DEBUG               
############## Server properties ###############
server:
  port: 8761
  shutdown: graceful
############## Eureka properties ###############  
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false